version: '3.8'

volumes:
  mongo_db_volume:

services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27000:27017"
    volumes:
      - mongo_db_volume:/data/db
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}

  tg_bot:
    build: .
    container_name: tg_bot
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - mongo_db
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
